[package]
name = "planitpoker-jira-upload-sanitizer"
version = "0.1.0"
authors = ["Christian Harke <christian@harke.ch>"]
edition = "2018"

[dependencies]
csv = "1.1"
quick-xml = { version = "0.20.0", features = [ "serialize" ] }
serde = { version = "1.0", features = [ "derive" ] }

